### ISSUE TITLE
kubernetes helm chart fails without additional undocumented steps

### ISSUE THREAD

**Issue by gianlazz** [BeryJu/authentik#741]
**Describe the bug**
> A clear and concise description of what the bug is.

When following the instructions for the kubernetes deployment via helm chart against my k3s homelab I've run into a few issues. The first is that the `helm install authentik/authentik --devel -f values.yaml` command failed for me without the addition of `--generate-name` at the end.

The second issue I ran into was that the helm chart seems to assume that prometheus is installed. It failed for me with the following error `Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]`.

I was able to overcome the `no matches for kind "PrometheusRule"` error by installing prometheus via the following helm commands:
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-prom-release bitnami/prometheus-operator
```

Additionally I'm seeing the following warning on both of my static and web pods `error while running "VolumeBinding" prebind plugin for pod "authentik-1618536529-static-7bbb74bcd7-fs754": Failed to bind volumes: timed out waiting for the condition`. I'm hoping this is just related to my cluster and will try restarting the pods to see if that gets things going.

**To Reproduce**
> Steps to reproduce the behavior:
I followed the steps as they're written in https://goauthentik.io/docs/installation/kubernetes

**Expected behavior**
> A clear and concise description of what you expected to happen.

I'd like to see these details either handled by the helm chart if that's appropriate, or documented as requirements.

**Logs**
> Output of docker-compose logs or kubectl logs respectively

Logs were mentioned in the section at the top.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.4.1
 - Deployment: helm against k3s cluster

**Additional context**

Other than this I just wanted to mention how excited I am about this project. I believe this project fills a major whole in the selfhosted community. Keep up the awesome work and looking forward to how the project develops!

**Comment by gianlazz** [comment]
Hmm looks like the `error while running "VolumeBinding" prebind plugin for pod "authentik-1618536529-static-7bbb74bcd7-fs754": Failed to bind volumes: timed out waiting for the condition` was due to k3s not coming with a default storage class.

- https://github.com/k3s-io/k3s/issues/85

I tried installing "local path provisioner" based on this link:
- https://github.com/k3s-io/k3s/issues/85#issuecomment-468293334

However I'm now getting `error while running "VolumeBinding" prebind plugin for pod "authentik-1618545250-static-6fbf47664f-hjrr6": Failed to bind volumes: timed out waiting for the condition` on the `web` and `static` pods.

**Comment by BeryJu** [comment]
Hey, I've just looked into this and noticed that I've had `monitoring.enabled` set to true by default, which requires the Prometheus CRDs. I'll change the default to false.

I'm not quite sure what the other errors are coming from, authentik does create some PVCs for uploads but it shouldn't cause any issues.

**Comment by BeryJu** [comment]
Is your k3s cluster running on multiple nodes? I think you might be running into storage issues as the PVCs are declared as RWX which your cluster might not have.

**Comment by gianlazz** [comment]
> Is your k3s cluster running on multiple nodes? I think you might be running into storage issues as the PVCs are declared as RWX which your cluster might not have. 

That could be it. I have one physical machine running k3OS configured as a master node for my Homelab.

**Comment by BeryJu** [comment]
I've made this configurable in helm using `pvc.mode: ReadWriteOnce`, it'll be included in the next minor update.

**Comment by gianlazz** [comment]
I've gone ahead and tried to make use of these changes with the following `values.yaml`:

```yaml
postgresql:
  postgresqlPassword: "generated-key"
redis:
  password: "generated-key"
config:
  secretKey: "generated-key"
pvc.mode: ReadWriteOnce
ingress:
  annotations:
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - authentik.internal.lazz.tech
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
```

However I'm encountering the following errors with bot the `static` and `web` pods:

`error while running "VolumeBinding" prebind plugin for pod "authentik-1618767851-web-b9cb96dc9-swnh6": Operation cannot be fulfilled on persistentvolumeclaims "authentik-1618767851-uploads": the object has been modified; please apply your changes to the latest version and try again`

`error while running "VolumeBinding" prebind plugin for pod "authentik-1618767851-static-6cfd6884dd-6wzf5": Failed to bind volumes: timed out waiting for the condition`

I suspect this may be due to my repeated attempts to install this via helm?

**Comment by BeryJu** [comment]
> ```pvc.mode: ReadWriteOnce```
I think within a values file you have to format it as 

```yaml
pvc:
  mode: ReadWriteOnce
```

I'm not sure where the error could come from, seems to be related with the PVC Provisioner, but not 100% sure. Can you try a clean install in another namespace, and see if that works?

**Comment by gianlazz** [comment]
> > ```pvc.mode: ReadWriteOnce```
> 
> I think within a values file you have to format it as 
> 
> 
> 
> ```yaml
> 
> pvc:
> 
>   mode: ReadWriteOnce
> 
> ```
> 
> 
> 
> I'm not sure where the error could come from, seems to be related with the PVC Provisioner, but not 100% sure. Can you try a clean install in another namespace, and see if that works?

Yup I'll try with the adjusted values format and a new namespace.

**Comment by gianlazz** [comment]
The following config from your suggestions has deployed successfully to my k3OS homelab, without having to change namespaces. Thank you very much for your help and thank you again for making an awesome selfhosted oriented sso solution!

```yaml
postgresql:
  postgresqlPassword: "generated-key"
redis:
  password: "generated-key"
config:
  secretKey: "generated-key"
pvc:
  mode: ReadWriteOnce
ingress:
  annotations:
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - authentik.internal.lazz.tech
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
```
