### ISSUE TITLE
Getting Error 500 with clean install

### ISSUE THREAD

**Issue by RacerBas** [BeryJu/authentik#749]
I just installed this but when I want to do the initial setup I get

API request failed

GET /api/v2beta/flows/executor/initial-setup/?query=: 500

Health checks in Traefik are up.

I did notice this in the logs alog with a lot of other errors:
2021/04/18 11:16:22 [error] 32#32: *7 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.90.254, server: _, request: "GET /favicon.ico HTTP/1.1", host: "authentik.mydomain.com", referrer: "https://authentik.mydomain.com/"
{"timestamp":"18/Apr/2021:11:16:22 +0000","host":"192.168.90.254","request_username":"","event":"GET /favicon.ico HTTP/1.1","status": "404","size":"186","runtime":"0.000","logger":"nginx","request_useragent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36 Edg/90.0.818.39"}

my config= 
```yaml
 authentik-server:
    image: beryju/authentik
    restart: unless-stopped
    container_name: authentik-server
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
    volumes:
      - $DOCKERDIR/authentik/server/media:/media
      - $DOCKERDIR/authentik/server/custom-templates:/templates
#      - geoip:/geoip
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`authentik.mydomain.com`) && PathPrefix(`/`)"
#      - "traefik.http.routers.authentik.middlewares=chain-authelia@file"
      - "traefik.http.routers.authentik.service=authentik-service"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.services.authentik-service.loadbalancer.healthcheck.path=/-/health/live/"
      - "traefik.http.services.authentik-service.loadbalancer.server.port=8000"
#      traefik.docker.network: internal
#      traefik.http.routers.app-router.rule: PathPrefix(`/`)
#      traefik.http.routers.app-router.service: app-service
#      traefik.http.routers.app-router.tls: 'true'
#      traefik.http.services.app-service.loadbalancer.healthcheck.path: /-/health/live/
#      traefik.http.services.app-service.loadbalancer.server.port: '8000'
    env_file:
      - .env
  authentik-worker:
    image: beryju/authentik
    restart: unless-stopped
    container_name: authentik-worker
    command: worker
    networks:
      - t2_proxy
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    volumes:
      - $DOCKERDIR/authentik/worker/backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/authentik/worker/custom-templates:/templates
#      - geoip:/geoip
    env_file:
      - .env
  authentik-static:
    image: beryju/authentik-static
    restart: unless-stopped
    container_name: authentik-static
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
#      - "traefik.docker.network=t2_proxy"
#      - "traefik.http.routers.authentik-static.middlewares=chain-authelia@file"
      - "traefik.http.routers.authentik-static.rule=Host(`authentik.mydomain.com`) && PathPrefix(`/static`, `/if`, `/media`, `/robots.txt`, `/favicon.ico`)"
      - "traefik.http.routers.authentik-static.tls=true"
      - "traefik.http.routers.authentik-static.service=static-service"
      - "traefik.http.services.static-service.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.static-service.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.static-service.loadbalancer.server.port=80"
    volumes:
      - $DOCKERDIR/authentik/static/media:/usr/share/nginx/html/media

```
